import React from "react";
import headerimages from '../images/headers_bro-eddie.jpg';

function BroEddie() {

    return(
<div>
    <div className="broeddie-content container bg-white p-5 rounded-3">
        <div>
            <h1><strong>Bro. Eddie</strong></h1>
            <img src={headerimages} className="img-fluid my-4"/>
            <p className="text-left"><strong>THE MAN, HIS MESSAGE AND THE MINISTRY<br/></strong></p>
            <p>From a communist-atheist to one of the most powerful preachers of God’s Word in the world today… From a radical activist to the founder-pastor of one of the largest Chr/ist-centered, Bible-based, full-gospel churches in the world… From a battle-scarred street parliamentarian to one of the most respected Chr/istian leaders in the Philippines whose spiritual counsel is sought after by high-ranking officials and distinguished leaders of the nation… From a persecuted “small, country preacher’ to a world-renown radio-TV evangelist, prophet and apostle whose vision and mission is to see the nations of the world evangelized and transformed by the same Gospel that changed his life.</p>
            <p>This in a capsule captures the exciting life story of Eddie Villanueva, fondly called Bro. Eddie or Bishop Eddie.</p>
            <hr/>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>LIFE-CHANGING ENCOUNTER<br/>
            </strong></p>
            <p>Bro. Eddie had a life-changing encounter with the Lord in 1973 while at the forefront of a leftist movement fighting against the evils of a vicious system that has perpetuated social injustice and massive deprivation in the country. At that time, he was also leading his family and other families in his home province of Bulacan (an hour away north of Manila) in an uphill, protracted legal battle against a notorious land-grabbing syndicate. Five days after that dramatic encounter with God, Bro. Eddie was brought face to face with a miracle he could never forget: the land-grabbers were arrested and detained. But a greater miracle took place in Bro. Eddie’s heart: The Holy Spirit “arrested” him. He became a true believer in the reality of a loving and powerful God! He surrendered his life to the Lord Jesus Chr/ist and soon after, his wife Dory also gave her life to the Lord.</p>
            <hr/>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>HUMBLE BEGINNINGS OF JIL<br/>
            </strong></p>
            <p> Bro. Eddie’s raging passion, fire and zeal for activism soon became a consuming passion for God, fire for the Gospel and zeal for evangelism. Out of the overflow of his spiritual turning point, he began to share Jesus with family members and friends, then in Bible studies and church gatherings. It was evident from the start that God’s special touch was upon this man, who, for years, was deeply immersed in Marxist dialectics, Leninist revolutionary tactics and thoughts of Mao Tse Tung.</p>
            <p>As professor of Economics and Finance at the Polytechnic University of the Philippines (PUP), his Alma Mater (where he now sits as a member of the Board of Regents), he seized every opportunity to proclaim the Gospel to his students, who in turn, responded with much fervor. Their lives were so touched that they urged their professor to teach them more about the Bible.</p>
            <p>Thus, the Jesus is Lord Church, popularly called JIL, was born. It was 1978. From a Bible study of 15 PUP students, it has exploded to a phenomenal constituency of over a million. It is considered the biggest in the Philippines today and one of the largest in the world. Today, Bro. Eddie’s ministry is also touching many millions more thr/ough his TV, radio, literature, audio-tape and video ministries, the JIL Chr/istian Schools/JIL Colleges Foundation, Inc. and thr/ough the JIL worldwide ministries.</p>
            <p>Bro. Eddie’s vision is to reach out to all Filipinos with the Gospel wherever they are – in the Philippines or in other countries- and to all nationalities in the four-corners of the earth. To pursue this vision, JIL has established chapters in Europe, US, Canada, Middle East, Northern Africa and neighboring Asian countries, reaching out mostly to expatriate Filipinos. Recently, God instructed Bro. Eddie to launch a massive evangelization campaign aimed at touching the major cities of the world with the transforming power of Jesus.</p>
            <hr/>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>TRIUMPHS AND TESTINGS<br/>
            </strong></p>
            <p> But the triumphs did not come without the concomitant testings. Bro. Eddie and his family have been at the receiving end of violent persecutions both from the enemy’s camp and from religious groups. They have been the object of several assassination attempts, the most horrible of which happened at about midnight on June 17, 1983. The whole family had just come from their church’s Friday night service and Bro. Eddie was about to enter their house in Bulacan when a grenade was thr/own his way and exploded a few feet from where he stood into 1200 deadly shr/apnel. The house front and part of the roof were shattered but not one shr/apnel hit Bro. Eddie. God protected and spared the life of His servant and his family!</p>
            <hr/>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>TRANSFORMING THE NATIONS<br/>
            </strong></p>
            <p>Bro. Eddie’s passion is not just for the evangelization but also the transformation of the Philippines and other nations to become the blessed nations of God declared in Psalm 33:12. In 1984, God gave Bro. Eddie a vision of a “bloody revolution that may come if the churches will not unite to win the country with the Gospel.” That vision gave birth to the Philippines for Jesus Movement or PJM, a broad alliance of churches and ministries with a nationwide constituency of millions. Under the leadership of Bro. Eddie as National Chairman, PJM has been actively engaged in its prophetic ministry to the nation leading mass-based activities and multi- media thr/usts designed to transform the nation and establish the lordship of Jesus in all realms of life and society.</p>
            <p>Bro. Eddie’s prophetic mandate, that of speaking the heart and mind of God to the nation, was confirmed in November 1986 thr/ough a powerful word of prophecy given by Dr. Ralph Mahoney, founder of World MAP, and a world-respected Chr/istian leader-statesman. Thr/ough the years that prophetic word has been reaffirmed by other distinguished global Chr/istian leaders such as Dr. Bill Hamon, Dr. Cindy Jacobs, Dr. Peter Wagner, to mention some.</p>
            <p>Today, thr/ough his two top-rated weekly TV programs (Diyos at Bayan and PJM Forum), God has expanded Bro. Eddie’s reach in pursuing his prophetic role. Also recently, in recognition of such mandate, he has unanimously been chosen to chair God’s People Coalition for Righteousness (GPCR), an aggrupation of concerned Catholics, Muslims and Evangelical Chr/istians, which aims to instill moral values in society and government.</p>
            <hr/>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>REACHING THE NATIONS BY TELEVISION<br/>
            </strong></p>
            <p>Early in their ministry, Bro. Eddie and Sis. Dory recognized the power of mass media in proclaiming the good news of salvation to millions. Thus, in 1982, they stepped out in bold faith, launched JIL’s Multimedia ministry and started the “Jesus the Healer” TV weekly program. The results were amazing: enormous numbers of people were exposed to the Gospel and multitudes came to the Lord and began attending JIL services. Bro. Eddie saw the effectiveness of TV as a medium for reaching whole cities and nations for Jesus!</p>
            <p>In 1984, in obedience to a word from God, Bro. Eddie started negotiations for the acquisition of Channel 11, the rights of which were owned by a very committed Chr/istian businessman. It was a quest that took about 14 long years to finish. It will take a whole book to chr/onicle the staggering yet exciting struggle for Channel 11 – the miraculous Hand of God that was evident all thr/oughout, the surprising turns and twists and the intense spiritual battle. Bro. Eddie knew that if the vision for Channel 11 was from God, ultimately, the victory would be at hand. Finally, on April 12, 1998, Channel 11 was dedicated for the glory of God. Even now, plans are already afoot on how to beam Gospel programs to the whole of Asia.</p>
            <hr/>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>”SECRETS” OF JIL’S SUCCESS<br/>
            </strong></p>
            <p>The phenomenal work of God thr/ough Bro. Eddie continues with more colorful chapters being added. Despite the remarkable fruitfulness of his ministry, it seems that God has something even greater for his chosen servant to fulfill. But the question is invariably asked: “What is the secret of this man?” He never had the opportunity to attend a formal Bible school but “why is he effective and why is God blessing his ministry tremendously?” </p>
            <p>Bro. Eddie’s standard reply reveals the heart of a real man of God: “it’s all because of God’s amazing grace.” When one takes a hard look at how God has prospered this man and his ministry, indeed, the only conclusion is: “it is only by His sovereign grace.”</p>
            <p>For the last 25 years, Bro. Eddie and JIL stand as classNameic examples of the practical outworking of such grace. If I can distill into some key thoughts (“secrets” if you will) why God has blessed the man and his ministry so enormously (yet in reality it is such that one can’t even begin to grasp) the following immediately grab the mind:</p>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>OBEDIENCE TO GOD’S CALL<br/>
            </strong></p>
            <p>A valid and God-blessed ministry always begins with a definite Call. The Bible shows us that when God plans to do something in the world, He first looks for someone He can use to fulfill His glorious purpose. He then calls that man, prepares and equips him, imparts His vision and sends him out. Such call gives the Called a sense of destiny, a vision. Unmistakably, this is Bro. Eddie’s experience.</p>
            <p>Thus thr/ough the years, he persevered to obey God’s call with holy passion, aggressively and fearlessly battling satanic onslaughts against him, his family and unique ministry (which is misunderstood even by some fellow Chr/istian leaders) because just like the men whom God called in the Old and New Testaments, he took hold of God’s vision for him and is fiercely determined to achieve it. Knowing this, Bro. Eddie literally gave up everything (his childhood ambition to become a topnotch lawyer and politician, a successful businessman, even his resources, etc.) and committed himself unreservedly to obey God. He exemplifies to all JIL people what total commitment is all about.</p>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>INTEGRITY and FIDELITY IN HIS PERSONAL AND FAMILY LIFE<br/>
            </strong></p>
            <p>Bro. Eddie models a leader who practices what he preaches. He demonstrates a contagious passion for God and a reverential fear of Him which have kept his personal/family life and ministry above reproach for 25 years, untainted by any hint of misdemeanor. God by His grace has indeed protected and preserved him from anything that would disgrace His name. This is not to say that the man had not suffered shortcomings or made honest mistakes which all ministers of the Gospel commit at times, despite their dedication to keep their integrity of heart. Bro. Eddie realizes that successful ministry is just the natural outflow of a life of integrity and fidelity in every arena of life, so he has purposed in his heart to be an example. </p>
            <p>Despite the bigness of his ministry, he always exudes genuine humility and servanthood. He is always careful to give glory to God for all the “successes” of JIL. Yet, he is always on a learning posture. He never fails to consult regularly fellow leaders and elders in the Body.</p>
            <p>Bro. Eddie learned early on that his family is top priority. He knows that his family validates his ministry and that without the witness of a strong family, really, he has no message to the world. He models a loving and faithful husband and a real father. Sis. Dory is a true, dedicated and excellent helpmeet always alongside her husband. As partners in ministry, they are truly twin towers of strength.</p>
            <p>Their prayerful guidance, has helped propel their children into divine placements where they are now enjoying significant success and impact: Jonjon is presently the Mayor of their hometown, Bocaue, in Bulacan and is one of the youngest mayors in the Philippines today; Joel Emmanuel, a Harvard graduate, was elected to the House of Representatives in 2001 and is the youngest (and certainly one of the brightest) Congressman in the country (he is called the Benjamin of Congress); Joni is not only a top-rated gospel singer/artist but also an able administrator. She is Executive Vice President and General Manager of Zoe TV – Channel 11. Jovi, the youngest is a brilliant and amiable junior at the country’s premier university for teachers and is deeply passionate for ministry.</p>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>FAITH to BELIEVE for the IMPOSSIBLE<br/>
            </strong></p>
            <p>As mentioned earlier, Bro. Eddie didn’t have the opportunity to attend formal schooling in a Bible school, but as a young Chr/istian and on to the early days of his ministry, he literally “devoured” books and tapes of ministry “greats” – successful healing evangelists and pastors such as Morris Cerullo, T.L. Osborn, Oral Roberts, Ralph Mahoney, Kenneth Hagin, to name some. These men plus the inputs of other local ministers helped shape the focus and thr/ust of Bro. Eddie’s preaching and ministry – that of walking in the realm of the miraculous, healing, faith, signs and wonders ministry. He was reared not just to believe in miracles but to rely on them; to see the invisible and believe God for the impossible!</p>
            <p>Thus, in JIL, the ministry of healing, miracles, signs and wonders are not just indispensable distinctives but common occurrences.</p>
            <p>Also, from the start, Bro. Eddie believed in the bigness of God and His power and grace to make JIL not just big but the biggest church– to give God the maximum glory! This reminds one of God’s promises to Abraham that his descendants will be as innumerable as the stars in heaven (Genesis 15: 5), dust of the earth (Gen. 13:16), sand on the seashore (Gen. 22:17). It is no big surprise then that JIL is big today (and counting!) and has been catapulted into such an enormous body underpinning Bro. Eddie’s prophetic voice.</p>
            <p>In fact (to inject a personal note here), at the rate God has been enlarging JIL, I envision it to become one of the 10 – 15 largest churches in the world with healthy, reproducing chapters all over the Philippines and in major cities of the globe led by cutting-edge leaders, having millions of discipled members who are reaching out to millions more thr/ough JIL’s Multi-ministries. I could see JIL exercising its apostolic and prophetic mandate to the Body of Chr/ist and to the nations and will be recognized more and more as a powerful transformational force (that no government can afford to ignore) in shaping the destiny of the Philippines and other countries until the return of our Lord Jesus Chr/ist.</p>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>MULTIPLICATION OF LEADERS<br/>
            </strong></p>
            <p>Bro. Eddie knew from the beginning that he can’t fulfill God’s mandate alone, so he focused on training and equipping able and faithful leaders. He adheres to the wise adage that there’s no real success until you have prepared your successors. JIL has grown phenomenally as it is today because it has teachable and loyal leaders who caught and run with the vision and pursued with discipline and zeal JIL’s priorities of evangelism and transformation. The JIL International Bible College which was established as a formal school in 2001 is dedicated to train more leaders for the end-time harvest. </p>
            <p> <strong></strong></p><strong>
            </strong><p className="text-left"><strong>VISION FOR THE WORLD<br/>
            </strong></p>
            <p>Bro. Eddie’s heartbeat is not just the Philippines but the whole world. He takes God’s command literally and seriously to “Go and preach the gospel to all creation… “ (Mark 16:15ff); “Go and make disciples of all nations…” (Matt. 28:18-20)</p>
            <p>His passion is to give each one in this world the opportunity to hear the Gospel and say yes to Jesus. To fulfill this, JIL has expanded to the continents of the world – reaching out to Filipinos first who will then be God’s bridges to other nations and cultures: JIL Hong Kong will reach out to China with its billion plus people; JIL European chapters will reach out to the French, Spanish, Italians, British, Dutch, Germans, and other Europeans; JIL North America will reach out to the Americans, Canadians and Hispanics and so on. Bro. Eddie and JIL will faithfully proclaim “the Gospel of the kingdom as a testimony to all nations” until the end will come.</p>
        </div>
    </div>
</div>
    )
}

export default BroEddie;